import Head from 'next/head';
import React from 'react';
import styles from '../styles/page.module.css';

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hola Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}> hello </main>

      <footer className={styles.footer}>
        <a href="https://vercel.com?">vercel</a>
      </footer>
    </div>
  );
};

export default Home;
