import Head from 'next/head';
import Image from 'next/image';
import React from 'react';
import { NextPage } from 'next';
import Link from 'next/link';
import styles from '../styles/page.module.css';

interface Props {
  data: Array<{
    id: string;
    title: string;
    description: string;
    image: string;
  }>;
}

const Home: NextPage<Props> = ({ data }) => {
  return (
    <>
      <Head>
        <title>Hola Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <header>
          <nav>
            <img />
            <Link href="/" passHref>
              Home
            </Link>
            <Link href="/events" passHref>
              Events
            </Link>
            <Link href="/about" passHref>
              About Us
            </Link>
          </nav>
        </header>

        <main className={styles.main}>
          {data.map((ev) => (
            <Link key={ev.id} href={`/events/${ev.id}`}>
              <Image width={300} height={300} alt={ev.title} src={ev.image} />{' '}
              <h2>{ev.title}</h2>
              <p>{ev.description}</p>
            </Link>
          ))}
        </main>

        <footer className={styles.footer}>
          <p>2023 Time to code - A project</p>
        </footer>
      </div>
    </>
  );
};

export default Home;

export async function getServerSideProps() {
  const { events_categories } = await import('/data/data.json');
  //console.log(events_categories);
  return {
    props: {
      // props for your component
      data: events_categories,
    },
  };
}
