import Head from 'next/head';

import React from 'react';
import { NextPage } from 'next';

// import styles from '../styles/page.module.css';
import HomePage from '@/components/home/home-page';

interface Props {
  data: Array<{
    id: string;
    title: string;
    description: string;
    image: string;
  }>;
}

const Home: NextPage<Props> = ({ data }) => {
  return (
    <>
      <Head>
        <title>Hola Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <HomePage data={data} /> */}
    </>
  );
};

export default Home;

export async function getServerSideProps() {
  const { events_categories } = await import('/data/data.json');
  //console.log(events_categories);
  return {
    props: {
      // props for your component
      data: events_categories,
    },
  };
}
